export const FETCH_MONGO_DATA_SUCCESS = 'FETCH_MONGO_DATA_SUCCESS';

export const FETCH_MONGO_DATA_ERROR = 'FETCH_MONGO_DATA_ERROR';

export const ADD_ITEM = 'ADD_ITEM';

export const TRYON_ITEM = 'TRYON_ITEM';

export const DELETE_ITEM = 'DELETE_ITEM';
