export const TURN_ON_ALERT = 'TURN_ON_ALERT'

export const TURN_OFF_ALERT = 'TURN_OFF_ALERT'

export const FETCH_MONGO_DATA_SUCCESS = 'FETCH_MONGO_DATA_SUCCESS';

export const FETCH_MONGO_DATA_ERROR = 'FETCH_MONGO_DATA_ERROR';

export const ADD_ITEM = 'ADD_ITEM';

export const TRYON_ITEM = 'TRYON_ITEM';

export const TAKEOFF_ITEM = 'TAKEOFF_ITEM';

export const DELETE_ITEM = 'DELETE_ITEM';


// export const DELETE_OUTFIT = 'DELETE_OUTFIT';